name: Fetch ERD Fire Datasets

on:
  schedule:
    # Runs at 21 minutes after every hour (UTC)
    - cron: "21 * * * *"
  workflow_dispatch: {}

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
      ACTIVE_FIRES_URL: "https://gis-erd-der.gnb.ca/arcgis/rest/services/Fire_Dashboards/Public_Fires/MapServer/0/query"
      OUT_FIRES_URL: "https://gis-erd-der.gnb.ca/arcgis/rest/services/Fire_Dashboards/Public_Fires/MapServer/1/query"
      SUMS_TABLE_URL: "https://gis-erd-der.gnb.ca/arcgis/rest/services/Fire_Dashboards/Public_Fires/MapServer/2/query"
      ACTIVE_FIRES_FILE: "active_fires.geojson"
      OUT_FIRES_FILE: "out_fires.geojson"
      SUMS_TABLE_FILE: "sums_table.json"
      GNB_SUM_FILE: "GNBfireActSum.json"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch ERD layers, validate, and write files
        shell: bash
        run: |
          set -euo pipefail

          python -u - << 'PYCODE'
          import os, time, json, hashlib
          import requests

          SESSION = requests.Session()
          SESSION.headers.update({"User-Agent": "github-actions ERD fetcher"})

          def log(msg):
              ts = time.strftime("%Y-%m-%d %H:%M:%S", time.gmtime())
              print(f"[{ts} UTC] {msg}", flush=True)

          def arcgis_get(url, params, *, attempts=3, timeout=60):
              for attempt in range(1, attempts + 1):
                  try:
                      r = SESSION.get(url, params=params, timeout=timeout)
                      if r.status_code == 200:
                          return r
                      log(f"HTTP {r.status_code} from {url} (attempt {attempt})")
                  except Exception as e:
                      log(f"Request error (attempt {attempt}): {e}")
                  time.sleep(1)
              raise RuntimeError(f"Failed after {attempts} attempts: {url}")

          # ---------- Schema helpers ----------
          def fetch_layer_meta(url):
              """Fetch layer metadata (fields, objectIdField, etc.)."""
              meta_url = url.rsplit("/query", 1)[0]
              r = arcgis_get(meta_url, {"f": "json"})
              meta = r.json()
              if not isinstance(meta, dict):
                  raise RuntimeError("Layer metadata not a dict")
              return meta

          def get_oid_field(meta):
              # Prefer 'objectIdField', else find the field with type esriFieldTypeOID, else common fallbacks
              if isinstance(meta.get("objectIdField"), str):
                  return meta["objectIdField"]
              for f in meta.get("fields", []):
                  if f.get("type") == "esriFieldTypeOID":
                      return f.get("name")
              for cand in ("OBJECTID","ObjectID","objectid"):
                  if any(cand == f.get("name") for f in meta.get("fields", [])):
                      return cand
              # last resort
              return "OBJECTID"

          def get_all_field_names(meta):
              return [f["name"] for f in meta.get("fields", []) if "name" in f]

          # ---------- Signatures for stability ----------
          def features_to_signature(feature_collection):
              feats = feature_collection.get("features", [])
              def feature_key(f):
                  props = f.get("properties", {})
                  if isinstance(props, dict):
                      for key in ("OBJECTID","ObjectID","objectid"):
                          if key in props:
                              return (0, props[key])
                  return (1, hashlib.sha256(json.dumps(props, sort_keys=True, ensure_ascii=False).encode("utf-8")).hexdigest())
              norm = []
              for f in feats:
                  props = f.get("properties", {}) or {}
                  strings = []
                  for k, v in props.items():
                      if isinstance(v, str):
                          strings.append(v)
                  strings.sort()
                  norm.append(("".join(strings), feature_key(f)))
              norm.sort(key=lambda t: t[1])
              concat = "|".join(s for s, _ in norm)
              return len(feats), hashlib.sha256(concat.encode("utf-8")).hexdigest()

          def table_to_signature(table_json):
              feats = table_json.get("features", [])
              rows = []
              for f in feats:
                  attrs = f.get("attributes", {}) or {}
                  strings = []
                  for k, v in attrs.items():
                      if isinstance(v, str):
                          strings.append(v)
                  strings.sort()
                  rows.append("".join(strings))
              rows.sort()
              concat = "|".join(rows)
              return len(feats), hashlib.sha256(concat.encode("utf-8")).hexdigest()

          # ---------- Fetchers ----------
          def fetch_geojson(url):
              """Get ArcGIS's own GeoJSON (keeps geometry shape identical to before)."""
              params = {
                  "where": "1=1",
                  "outFields": "*",
                  "outSR": "4326",
                  "returnGeometry": "true",
                  "f": "geojson",
              }
              r = arcgis_get(url, params)
              data = r.json()
              if isinstance(data, dict) and data.get("error"):
                  raise RuntimeError(f"ArcGIS error (geojson): {data['error']}")
              if data.get("type") != "FeatureCollection":
                  raise RuntimeError("GeoJSON did not contain a FeatureCollection")
              return data

          def attributes_index_by_oid(attrs_json, oid_field):
              index = {}
              for f in attrs_json.get("features", []):
                  attrs = f.get("attributes") or {}
                  if oid_field in attrs:
                      index[attrs[oid_field]] = attrs
              return index

          # ---------- Merge ----------
          def merge_geojson_with_attrs(geojson_obj, attrs_by_oid, all_fields, oid_field):
              for f in geojson_obj.get("features", []):
                  props = f.get("properties")
                  if props is None or not isinstance(props, dict):
                      props = {}
                      f["properties"] = props
                  oid_val = props.get(oid_field)
                  source = attrs_by_oid.get(oid_val, {})
                  # Ensure all fields exist; fill if missing or None
                  for name in all_fields:
                      if name not in props or props[name] is None:
                          if name in source:
                              props[name] = source[name]
                          else:
                              # still ensure the key exists for consistency
                              if name not in props:
                                  props[name] = None
              return geojson_obj

          def add_timestamp_to_geojson(data, timestamp):
              feats = data.get("features", [])
              for f in feats:
                  if "properties" not in f or not isinstance(f["properties"], dict):
                      f["properties"] = {}
                  f["properties"]["FETCHED_FROM_ERD"] = int(timestamp)
              return data

          def add_timestamp_to_table(data, timestamp):
              feats = data.get("features", [])
              for f in feats:
                  attrs = f.get("attributes")
                  if attrs is None or not isinstance(attrs, dict):
                      f["attributes"] = {}
                      attrs = f["attributes"]
                  attrs["FETCHED_FROM_ERD"] = int(timestamp)
              return data

          # ---------- Orchestrated fetch with stability check ----------
          def attempt_fetch_geojson_with_full_attrs(kind, url, outfile, max_attempts=5, copies=4):
              meta = fetch_layer_meta(url)
              oid_field = get_oid_field(meta)
              all_fields = get_all_field_names(meta)
              log(f"{kind}: OID field='{oid_field}', fields={len(all_fields)}")

              for attempt in range(1, max_attempts + 1):
                  log(f"=== {kind}: attempt {attempt}/{max_attempts} ===")
                  payloads = []
                  sigs = []
                  for i in range(copies):
                      base_geo = fetch_geojson(url)                     # geometry + some attrs
                      attrs_json_resp = arcgis_get(url, {
                          "where": "1=1",
                          "outFields": "*",
                          "returnGeometry": "false",
                          "f": "json",
                      }).json()                                         # full attrs only
                      attrs_by_oid = attributes_index_by_oid(attrs_json_resp, oid_field)

                      merged = merge_geojson_with_attrs(base_geo, attrs_by_oid, all_fields, oid_field)
                      count, sig = features_to_signature(merged)
                      payloads.append(merged)
                      sigs.append((count, sig))
                      log(f"{kind}: copy {i+1}/{copies} -> features={count} sig={sig[:12]}")
                      time.sleep(1)

                  ok = all(sigs[0] == s for s in sigs[1:])
                  if not ok:
                      log(f"{kind}: copies mismatch on attempt {attempt}; retrying …")
                      continue

                  ts = int(time.time())
                  final = add_timestamp_to_geojson(payloads[0], ts)
                  with open(outfile, "w", encoding="utf-8") as f:
                      json.dump(final, f, ensure_ascii=False, indent=2)
                  log(f"{kind}: wrote {outfile} (features={sigs[0][0]})")
                  return True

              log(f"{kind}: FAILED after {max_attempts} attempts")
              return False

          def attempt_fetch_table_json(kind, url, outfile, max_attempts=5, copies=4):
              for attempt in range(1, max_attempts + 1):
                  log(f"=== {kind}: attempt {attempt}/{max_attempts} ===")
                  payloads = []
                  sigs = []
                  for i in range(copies):
                      params = {
                          "where": "1=1",
                          "outFields": "*",
                          "returnGeometry": "false",
                          "f": "json"
                      }
                      r = arcgis_get(url, params)
                      data = r.json()
                      if isinstance(data, dict) and data.get("error"):
                          raise RuntimeError(f"ArcGIS error for {kind}: {data['error']}")
                      payloads.append(data)
                      count, sig = table_to_signature(data)
                      sigs.append((count, sig))
                      log(f"{kind}: copy {i+1}/{copies} -> rows={count} sig={sig[:12]}")
